[package]
authors = ["David Wallace Croft <david@croftsoft.com>"]
categories = ["games", "simulation"]
description = "Conway's Game of Life"
edition = "2024"
homepage = "https://www.croftsoft.com/"
keywords = ["rust", "wasm"]
license = "MIT"
name = "com-croftsoft-app-life"
publish = false
readme = "README.md"
repository = "https://github.com/david-wallace-croft/com-croftsoft-app-life"
rust-version = "1.98"
version = "0.5.1-SNAPSHOT"

[dependencies]
anyhow = "~1.0.104"
com-croftsoft-lib-animation = "~0.1.0"
com-croftsoft-lib-role = "~0.5.1"
console_error_panic_hook = "~0.1.7"
futures = "~0.3.34"
js-sys = "~0.3.105"
wasm-bindgen = "~0.2.128"
wasm-bindgen-futures = "~0.4.78"

[dependencies.web-sys]
features = [
  "CanvasRenderingContext2d",
  "Document",
  "DomRect",
  "Element",
  "Event",
  "HtmlCanvasElement",
  "HtmlCollection",
  "HtmlDivElement",
  "HtmlInputElement",
  "MouseEvent",
  "Performance",
  "Window",
  "console",
]
version = "~0.3.104"

[dev-dependencies]
wasm-bindgen-test = "~0.3.77"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
